### ISSUE TITLE
XXMI Launcher not opening

### ISSUE THREAD

**Issue by Lowyk** [SpectrumQT/XXMI-Launcher#48]
> OS: Windows 10 22H2
> AV is not installed

When i open XXMI Launcher it doesn't do anything, it worked like 3 days ago.

**What have i tried:**

- Re-installing VC++
- Re-installing XXMI Launcher
- Rebooting PC
- Using other versions of XXMI Launcher

**Comment by Lowyk** [comment]
> Does it write anything to log file in its folder?

Where is the log file? I'll check

**Comment by SpectrumQT** [comment]
Unfortunately, the issue cannot be further researched in this case, as only possible way to find out the reason is to run x64 debugger session on your PC, and I'm not providing such services. Most likely (statistically speaking) your OS is somehow damaged, and I can only suggest to try reinstall it from original MSDN image.
