### ISSUE TITLE
False positive? Or true? In d3d11.dll

### ISSUE THREAD

**Issue by whitevamp** [SpectrumQT/XXMI-Launcher#64]
After the most recent update [ver1.3.0](https://github.com/SpectrumQT/XXMI-Launcher/releases/tag/v1.3.0) I am getting a virus warning now, is this a false positive? Or?
<img width="286" alt="{4D3687C5-AF3E-46A0-9B50-DCED2C497FFD}" src="https://github.com/user-attachments/assets/2a5c1803-9f6c-42e2-b781-85cbd139cae1" />

**Comment by Drax-5** [comment]
I was wondering this too, thinking I downloaded a fake but it still popped up. Probably a false positive but i'd rather to stay on the safer side tbh

**Comment by whitevamp** [comment]
> I was wondering this too, thinking I downloaded a fake but it still popped up. Probably a false positive but i'd rather to stay on the safer side tbh

I agree.

**Comment by SpectrumQT** [comment]
The trigger is caused by Windows Defender's machine learning module (`ml` in the threat name). Whether to trust Microsoft's neural network or the fact that [no dedicated paid AVs are getting triggered](https://www.virustotal.com/gui/file/8a595742304fa71185a2c1173a851e0bdc61d220b6c26a6ec589b7738d4bb21a), it's up to you.

Also you can build the DLL yourself from [its sources](https://github.com/SpectrumQT/3Dmigoto) with Visual Studio 2022 and use it instead (in this case don't forget to enable Unsafe Mode in Advanced Settings to make launcher ignore signature mismatch).

**Comment by whitevamp** [comment]
> I was wondering this too, thinking I downloaded a fake but it still popped up. Probably a false positive but i'd rather to stay on the safer side tbh

I agree.

> The trigger is caused by Windows Defender's machine learning module (`ml` in the threat name). Whether to trust Microsoft's neural network or the fact that [no dedicated paid AVs are getting triggered](https://www.virustotal.com/gui/file/8a595742304fa71185a2c1173a851e0bdc61d220b6c26a6ec589b7738d4bb21a), it's up to you.
> 
> Also you can build the DLL yourself from [its sources](https://github.com/SpectrumQT/3Dmigoto) with Visual Studio 2022 and use it instead (in this case don't forget to enable Unsafe Mode in Advanced Settings to make launcher ignore signature mismatch).

Ok thank you for the reply, I had figured that it was a false positive, but thought I would ask, since this did not happen before, even though it was posted about a possible false positive event accruing, and even having checked the Signature.

I will close this thread now, and thanks once more.
